project_id = "juvywnnpcbhwarhwxcgc"

[functions.check-coupon-alerts]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.admin-grant-role]
verify_jwt = false

[functions.admin-banners]
verify_jwt = false
