project_id = "juvywnnpcbhwarhwxcgc"

[functions.check-coupon-alerts]
verify_jwt = false

[functions.stripe-connect-onboarding]
verify_jwt = false

[functions.stripe-create-payment]
verify_jwt = false

[functions.stripe-check-account]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-verify-payment]
verify_jwt = false

[functions.stripe-reconcile-orders]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false
