
TRUNCATE TABLE
  public.profiles,
  public.products,
  public.product_variations,
  public.product_price_tiers,
  public.product_drafts,
  public.user_roles,
  public.supplier_subscriptions,
  public.supplier_shipping_config,
  public.supplier_shipping_regions,
  public.supplier_applications,
  public.supplier_categories,
  public.notifications,
  public.notification_preferences,
  public.notification_sent_events,
  public.orders,
  public.messages,
  public.negotiations,
  public.disputes,
  public.reviews,
  public.reports,
  public.activity_logs,
  public.analytics,
  public.login_attempts,
  public.phone_verification_codes,
  public.product_views,
  public.price_history,
  public.push_notification_logs,
  public.push_subscriptions,
  public.collection_items,
  public.collection_members,
  public.collections,
  public.addresses,
  public.banners,
  public.support_tickets
RESTART IDENTITY CASCADE;
